import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase, configured } from "./supabase";
import Dashboard from "./Dashboard";
import FinanceCenter from "./FinanceCenter";
import { CATEGORIES, TYPES, STATUS, ROLES, PERIODS, money, num, margin, cost, price, profit, totals, periodRange } from "./constants";

function Login() {
  const [form,setForm]=useState({email:"",password:""}),[message,setMessage]=useState("");
  const submit=async(e)=>{e.preventDefault();setMessage("Entrando...");const r=await supabase.auth.signInWithPassword(form);setMessage(r.error?"E-mail ou senha inválidos.":"")};
  return <main className="auth-page"><section className="auth-card"><Brand/><p className="eyebrow">Acesso seguro</p><h1>Entrar</h1><p className="muted">Use o acesso fornecido pelo administrador.</p><form onSubmit={submit}><label>E-mail<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Senha<input type="password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button className="btn primary full">Entrar</button></form>{message&&<p className="auth-message">{message}</p>}</section></main>;
}
function Brand(){return <div className="brand auth-brand"><img className="brand-logo" src="/logo-mark.png" alt="Verdurão Ribeiro" width="48" height="48"/><div><strong>VERDURÃO RIBEIRO</strong><span>Controle CEASA</span></div></div>}
function Stat({label,value,note}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}

export default function App(){
  const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[stores,setStores]=useState([]),[selectedStoreId,setSelectedStoreId]=useState(""),[products,setProducts]=useState([]),[lists,setLists]=useState([]),[selectedListId,setSelectedListId]=useState(null),[items,setItems]=useState([]),[allItems,setAllItems]=useState([]),[expenses,setExpenses]=useState([]),[entries,setEntries]=useState([]),[entryCategories,setEntryCategories]=useState([]),[cashFlow,setCashFlow]=useState([]),[dailyRevenue,setDailyRevenue]=useState([]),[cashOpenings,setCashOpenings]=useState([]),[cashClosings,setCashClosings]=useState([]),[monthlyResults,setMonthlyResults]=useState([]),[auditLog,setAuditLog]=useState([]),[financeCategories,setFinanceCategories]=useState([]),[margins,setMargins]=useState({}),[view,setView]=useState("dashboard"),[search,setSearch]=useState(""),[category,setCategory]=useState(""),[period,setPeriod]=useState("mes"),[customStart,setCustomStart]=useState(""),[customEnd,setCustomEnd]=useState(""),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[dark,setDark]=useState(false);
  const isAdmin=profile?.role==="administrador",isManager=profile?.role==="gerente",canPlan=["administrador","gerente","funcionario"].includes(profile?.role),canBuy=["administrador","gerente","comprador"].includes(profile?.role),canFinance=isAdmin||isManager;
  const range=periodRange(period,customStart,customEnd), operationalStoreId=selectedStoreId==="all"?"":selectedStoreId;
  const storeProducts=products.filter(p=>p.store_id===operationalStoreId),storeLists=lists.filter(l=>l.store_id===operationalStoreId),activeList=storeLists.find(l=>l.id===selectedListId)||storeLists.find(l=>l.status==="aberta")||storeLists[0];
  const canEditPlan=canPlan&&activeList?.status==="aberta",canEditPurchase=canBuy&&activeList?.status==="aberta";
  const flash=t=>{setNotice(t);setTimeout(()=>setNotice(""),2600)};
  const load=useCallback(async()=>{
    if(!session)return;
    const [pr,st,ps,ls,ms,fc,ex,ai,au,ec,en,cf,dr,co,cc,mr]=await Promise.all([
      supabase.from("profiles").select("*").eq("id",session.user.id).single(),
      supabase.from("stores").select("*").eq("active",true).order("name"),
      supabase.from("products").select("*").eq("active",true).order("name"),
      supabase.from("shopping_lists").select("*, store:stores(*)").order("created_at",{ascending:false}).limit(100),
      supabase.from("category_margins").select("*"),
      supabase.from("financial_categories").select("*").eq("active",true).order("name"),
      supabase.from("expenses").select("*, store:stores(*), category:financial_categories(*)").order("expense_date",{ascending:false}),
      supabase.from("list_items").select("*, product:products(*), list:shopping_lists(*)"),
      supabase.from("audit_log").select("*").order("changed_at",{ascending:false}).limit(20),
      supabase.from("financial_entry_categories").select("*").eq("active",true).order("name"),
      supabase.from("financial_entries").select("*, store:stores(*), category:financial_entry_categories(*)").order("entry_date",{ascending:false}),
      supabase.from("cash_flow").select("*, store:stores(*)").order("movement_date",{ascending:false}),
      supabase.from("daily_revenue").select("*, store:stores(*)").order("revenue_date",{ascending:false}),
      supabase.from("cash_openings").select("*").order("opening_date",{ascending:false}),
      supabase.from("cash_closings").select("*").order("closing_date",{ascending:false}),
      supabase.from("monthly_results").select("*").order("result_month",{ascending:false})
    ]);
    setProfile(pr.data);setStores(st.data||[]);setProducts(ps.data||[]);setLists(ls.data||[]);setMargins(Object.fromEntries((ms.data||[]).map(x=>[x.category,x.margin])));setFinanceCategories(fc.data||[]);setExpenses(ex.data||[]);setAllItems(ai.data||[]);setAuditLog(au.data||[]);setEntryCategories(ec.data||[]);setEntries(en.data||[]);setCashFlow(cf.data||[]);setDailyRevenue(dr.data||[]);setCashOpenings(co.data||[]);setCashClosings(cc.data||[]);setMonthlyResults(mr.data||[]);
    const initialStore=selectedStoreId||(pr.data?.role==="administrador"?"all":pr.data?.store_id||st.data?.[0]?.id);
    if(initialStore!==selectedStoreId)setSelectedStoreId(initialStore);
    setLoading(false);
  },[session,selectedStoreId]);
  const loadListItems=useCallback(async()=>{
    if(!activeList){setItems([]);return}
    if(activeList.id!==selectedListId)setSelectedListId(activeList.id);
    const {data}=await supabase.from("list_items").select("*, product:products(*)").eq("list_id",activeList.id).order("created_at");setItems(data||[]);
  },[activeList,selectedListId]);
  useEffect(()=>{if(!configured)return;supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
  useEffect(()=>{load()},[load]);useEffect(()=>{loadListItems()},[loadListItems]);
  useEffect(()=>{if(!session)return;const ch=supabase.channel("app-live").on("postgres_changes",{event:"*",schema:"public",table:"list_items"},load).on("postgres_changes",{event:"*",schema:"public",table:"shopping_lists"},load).on("postgres_changes",{event:"*",schema:"public",table:"expenses"},load).on("postgres_changes",{event:"*",schema:"public",table:"financial_entries"},load).on("postgres_changes",{event:"*",schema:"public",table:"daily_revenue"},load).on("postgres_changes",{event:"*",schema:"public",table:"cash_openings"},load).on("postgres_changes",{event:"*",schema:"public",table:"cash_closings"},load).subscribe();return()=>supabase.removeChannel(ch)},[session,load]);
  const updateItem=async(id,patch)=>{const{error}=await supabase.from("list_items").update(patch).eq("id",id);if(error)flash(error.message);else{load();loadListItems()}};
  const createList=async()=>{if(!operationalStoreId)return flash("Selecione uma loja antes de criar a lista.");const title=prompt("Nome da nova lista:",`Compra ${new Date().toLocaleDateString("pt-BR")}`);if(!title)return;const{data,error}=await supabase.from("shopping_lists").insert({title,created_by:session.user.id,store_id:operationalStoreId}).select().single();if(error)flash(error.message);else{setSelectedListId(data.id);setView("lista");load()}};
  const addProduct=async()=>{if(!operationalStoreId)return flash("Selecione uma loja.");const name=prompt("Nome do produto:");if(!name)return;const cat=prompt("Categoria: fruta, verdura, legume, tempero ou outros","outros");const{error}=await supabase.from("products").insert({name,category:CATEGORIES[cat]?cat:"outros",purchase_unit:"kg",type:"normal",store_id:operationalStoreId});if(error)flash(error.message);else load()};
  const addToList=async(product_id)=>{if(!activeList||activeList.status!=="aberta")return flash("Crie ou abra uma lista ativa.");const{error}=await supabase.from("list_items").insert({list_id:activeList.id,product_id});if(error)flash(error.message);else{load();loadListItems()}};
  const filtered=useMemo(()=>items.filter(i=>(!search||i.product.name.toLowerCase().includes(search.toLowerCase()))&&(!category||i.product.category===category)),[items,search,category]);
  const t=totals(items,margins),bought=items.filter(i=>i.status==="comprado");
  if(!configured)return <main className="auth-page"><h2>Configure as variáveis do Supabase.</h2></main>;if(!session)return <Login/>;if(loading)return <main className="auth-page"><h2>Carregando Verdurão Ribeiro...</h2></main>;
  const nav=[["dashboard","▦","Dashboard"],["lista","☷","Lista"],["comprador","✓","Comprar"],["historico","◷","Listas"],...(canFinance?[["financeiro","$","Centro Financeiro"]]:[]),["relatorios","▥","Relatórios"],["config","⚙","Ajustes"]];
  return <div className={dark?"dark app-shell":"app-shell"}><header className="topbar"><Brand/><div className="header-actions"><select className="store-selector" value={selectedStoreId} onChange={e=>{setSelectedStoreId(e.target.value);setSelectedListId(null)}}>{isAdmin&&<option value="all">Todas as lojas</option>}{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="icon-btn" onClick={()=>setDark(!dark)}>{dark?"☀":"◐"}</button><button className="profile-btn" onClick={()=>supabase.auth.signOut()}><span>{ROLES[profile?.role]}</span><b>{(profile?.full_name||session.user.email)[0].toUpperCase()}</b></button></div></header>
  <nav className="nav">{nav.map(([id,ico,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><span>{ico}</span>{label}</button>)}</nav>
  <main><PeriodFilters period={period} setPeriod={setPeriod} customStart={customStart} setCustomStart={setCustomStart} customEnd={customEnd} setCustomEnd={setCustomEnd}/>
  {view==="dashboard"&&<Dashboard stores={stores} items={allItems} expenses={expenses} margins={margins} selectedStoreId={selectedStoreId} range={range} showFinance={canFinance}/>}
  {view==="lista"&&(operationalStoreId?<ListView activeList={activeList} items={items} filtered={filtered} products={storeProducts} margins={margins} totals={t} bought={bought} canPlan={canPlan} canEditPlan={canEditPlan} search={search} setSearch={setSearch} category={category} setCategory={setCategory} createList={createList} addProduct={addProduct} addToList={addToList} updateItem={updateItem}/>:<SelectStore/>)}
  {view==="comprador"&&(operationalStoreId?<Buyer items={items} margins={margins} canBuy={canEditPurchase} updateItem={updateItem} totals={t} activeList={activeList} userId={session.user.id} reload={load} flash={flash}/>:<SelectStore/>)}
  {view==="historico"&&(operationalStoreId?<History lists={storeLists.slice(0,20)} selectedListId={activeList?.id} selectList={id=>{setSelectedListId(id);setView("lista")}} createList={createList} canPlan={canPlan}/>:<SelectStore/>)}
  {view==="financeiro"&&canFinance&&<FinanceCenter expenses={expenses} entries={entries} entryCategories={entryCategories} cashFlow={cashFlow} dailyRevenue={dailyRevenue} cashOpenings={cashOpenings} cashClosings={cashClosings} monthlyResults={monthlyResults} items={allItems} stores={stores} categories={financeCategories} selectedStoreId={selectedStoreId} profile={profile} range={range} reload={load} flash={flash}/>}
  {view==="relatorios"&&<Reports items={allItems.filter(i=>(selectedStoreId==="all"||i.list?.store_id===selectedStoreId)&&i.list?.purchase_date>=range.start&&i.list?.purchase_date<=range.end)} margins={margins}/>}
  {view==="config"&&<Settings stores={stores} profile={profile} margins={margins} isAdmin={isAdmin} auditLog={auditLog} reload={load} flash={flash}/>}
  </main>{notice&&<div className="toast show">{notice}</div>}</div>
}

function PeriodFilters(p){return <div className="period-bar"><b>Período</b><select value={p.period} onChange={e=>p.setPeriod(e.target.value)}>{Object.entries(PERIODS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{p.period==="personalizado"&&<><input type="date" value={p.customStart} onChange={e=>p.setCustomStart(e.target.value)}/><input type="date" value={p.customEnd} onChange={e=>p.setCustomEnd(e.target.value)}/></>}</div>}
function SelectStore(){return <div className="empty"><b>Selecione uma loja</b><span>Escolha Santa Rita ou Taquari no topo para lançar informações.</span></div>}
function ListView(p){return <><div className="page-head"><div><p className="eyebrow">{p.activeList?.status==="finalizada"?"Lista finalizada · somente consulta":"Sincronizada em tempo real"}</p><h1>{p.activeList?.title||"Lista de compra"}</h1><p>Planejamento da loja selecionada.</p></div>{p.canPlan&&<div className="head-actions"><button className="btn secondary" onClick={p.createList}>Nova lista</button><button className="btn primary" onClick={p.addProduct}>+ Cadastrar produto</button></div>}</div><div className="stats"><Stat label="Na lista" value={p.items.length} note={`${p.bought.length} comprados`}/><Stat label="Total gasto" value={money(p.totals.spent)} note="CEASA"/><Stat label="Venda estimada" value={money(p.totals.sale)} note="preços sugeridos"/><Stat label="Lucro bruto" value={money(p.totals.gross)} note="estimado"/></div><div className="toolbar"><label className="search"><span>⌕</span><input placeholder="Buscar produto..." value={p.search} onChange={e=>p.setSearch(e.target.value)}/></label><select value={p.category} onChange={e=>p.setCategory(e.target.value)}><option value="">Todas as categorias</option>{Object.entries(CATEGORIES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button className="btn ghost" onClick={()=>window.print()}>Imprimir / PDF</button></div><div className="product-grid">{p.filtered.map(i=><ProductCard key={i.id} item={i} margins={p.margins} canPlan={p.canEditPlan} updateItem={p.updateItem}/>)}</div>{p.canEditPlan&&<section className="panel catalog-panel"><h3>Adicionar produto à lista</h3><div className="compact-products">{p.products.filter(x=>!p.items.some(i=>i.product_id===x.id)).map(x=><div className="catalog-row" key={x.id}><span><b>{x.name}</b> · {CATEGORIES[x.category]}</span><button className="btn secondary" onClick={()=>p.addToList(x.id)}>Adicionar</button></div>)}</div></section>}</>}
function ProductCard({item,margins,canPlan,updateItem}){return <article className="product-card"><div className="card-top"><div className="product-icon">●</div><span className={`chip ${item.status}`}>{STATUS[item.status]}</span></div><h3>{item.product.name}</h3><div className="sub">{CATEGORIES[item.product.category]} · {item.product.purchase_unit}</div><div className="chips"><span className="chip">{TYPES[item.product.type]}</span><span className="chip">Margem {margin(item,margins)}%</span></div><div className="card-numbers"><div><span>Planejado</span><b>{num(item.planned_quantity)}</b></div><div><span>Valor pago</span><b>{money(item.paid_total)}</b></div><div><span>Custo base</span><b>{money(cost(item))}</b></div><div><span>Venda sugerida</span><b>{money(price(item,margins))}</b></div></div>{canPlan&&<div className="card-actions"><button onClick={()=>updateItem(item.id,{planned_quantity:Number(prompt("Quantidade planejada:",item.planned_quantity)||item.planned_quantity)})}>Planejar</button><button onClick={()=>updateItem(item.id,{status:item.status==="nao_comprar"?"comprar":"nao_comprar"})}>Remover</button></div>}</article>}
function Buyer({items,margins,canBuy,updateItem,totals:tt,activeList,userId,reload,flash}){const finish=async()=>{if(!confirm("Finalizar esta compra?"))return;const{error}=await supabase.from("shopping_lists").update({status:"finalizada",finalized_by:userId,finalized_at:new Date().toISOString()}).eq("id",activeList.id);if(error)flash(error.message);else reload()};return <><div className="page-head"><div><p className="eyebrow">Modo comprador</p><h1>Compra no CEASA</h1><p>Valores sincronizados por loja.</p></div>{canBuy&&activeList&&<button className="btn success" onClick={finish}>Finalizar compra</button>}</div><div className="stats"><Stat label="Comprados" value={`${items.filter(i=>i.status==="comprado").length}/${items.length}`}/><Stat label="Total gasto" value={money(tt.spent)}/><Stat label="Venda estimada" value={money(tt.sale)}/><Stat label="Lucro bruto" value={money(tt.gross)}/></div><div className="buyer-list">{items.filter(i=>i.status!=="nao_comprar").map(i=><BuyerRow key={i.id} item={i} margins={margins} disabled={!canBuy} updateItem={updateItem}/>)}</div></>}
function BuyerRow({item,margins,disabled,updateItem}){const f=(key,label,type="number")=><label>{label}<input disabled={disabled} type={type} defaultValue={item[key]||""} onBlur={e=>updateItem(item.id,{[key]:type==="number"?Number(e.target.value):e.target.value})}/></label>;return <article className={`buyer-card ${item.status==="comprado"?"done":""}`}><div className="buyer-info"><h3>{item.product.name}</h3><p>Planejado: {num(item.planned_quantity)}</p></div>{f("purchased_quantity","Quantidade")}{f("weight_kg","Peso kg")}{f("paid_total","Valor pago")}<label>Qualidade<select disabled={disabled} value={item.quality} onChange={e=>updateItem(item.id,{quality:e.target.value})}>{["excelente","boa","regular","ruim"].map(x=><option key={x}>{x}</option>)}</select></label>{f("observation","Observação","text")}<div className="calc-box"><span>Custo</span><b>{money(cost(item))}</b><span>Venda</span><b>{money(price(item,margins))}</b></div><button disabled={disabled} className="btn success" onClick={()=>updateItem(item.id,{status:item.status==="comprado"?"comprar":"comprado"})}>{item.status==="comprado"?"Comprado ✓":"Marcar comprado"}</button></article>}
function History({lists,selectedListId,selectList,createList,canPlan}){return <><div className="page-head"><div><p className="eyebrow">Últimas 20 listas</p><h1>Histórico da loja</h1></div>{canPlan&&<button className="btn primary" onClick={createList}>+ Nova lista</button>}</div><div className="history-cards">{lists.map(l=><article className={`history-card ${l.id===selectedListId?"selected":""}`} key={l.id}><div><span className={`chip ${l.status}`}>{l.status}</span><h3>{l.title}</h3><p>{new Date(l.purchase_date+"T12:00").toLocaleDateString("pt-BR")}</p></div><button className="btn secondary" onClick={()=>selectList(l.id)}>Abrir lista</button></article>)}</div></>}
function Reports({items,margins}){const bought=items.filter(i=>i.status==="comprado"),t=totals(bought,margins);return <><div className="page-head"><div><p className="eyebrow">Relatórios por loja e período</p><h1>Relatórios CEASA</h1></div></div><div className="stats"><Stat label="Total gasto" value={money(t.spent)}/><Stat label="Venda estimada" value={money(t.sale)}/><Stat label="Lucro bruto" value={money(t.gross)}/><Stat label="Margem" value={`${num(t.spent?t.gross/t.spent*100:0)}%`}/></div><div className="report-grid"><article className="panel"><h3>Produtos mais caros</h3>{[...bought].sort((a,b)=>b.paid_total-a.paid_total).slice(0,10).map(i=><div className="rank-row" key={i.id}><span>{i.product?.name}</span><b>{money(i.paid_total)}</b></div>)}</article><article className="panel"><h3>Menor lucro estimado</h3>{[...bought].sort((a,b)=>profit(a,margins)-profit(b,margins)).slice(0,10).map(i=><div className="rank-row" key={i.id}><span>{i.product?.name}</span><b>{money(profit(i,margins))}</b></div>)}</article></div></>}
function Settings({stores,profile,margins,isAdmin,auditLog,reload,flash}){const addStore=async()=>{const name=prompt("Nome da nova loja:");if(!name)return;const{error}=await supabase.from("stores").insert({name});if(error)flash(error.message);else reload()};const updateMargin=async(c,v)=>{const{error}=await supabase.from("category_margins").update({margin:Number(v)}).eq("category",c);if(error)flash(error.message);else reload()};return <><div className="page-head"><div><p className="eyebrow">Conta, lojas e regras</p><h1>Configurações</h1><p>Seu perfil: {ROLES[profile.role]}</p></div>{isAdmin&&<button className="btn primary" onClick={addStore}>+ Cadastrar loja</button>}</div><div className="settings-grid"><article className="panel"><h3>Lojas cadastradas</h3>{stores.map(s=><div className="rank-row" key={s.id}><span>{s.name}</span><b>{s.active?"Ativa":"Inativa"}</b></div>)}</article><article className="panel"><h3>Margens por categoria</h3>{Object.entries(CATEGORIES).map(([k,v])=><div className="margin-setting" key={k}><b>{v}</b><input disabled={!isAdmin} type="number" defaultValue={margins[k]} onBlur={e=>updateMargin(k,e.target.value)}/></div>)}</article><article className="panel wide"><h3>Permissões</h3><p className="muted">Administrador acessa todas as lojas e o dashboard geral. Gerente acessa a loja vinculada e o financeiro. Funcionário cria listas sem ver o financeiro. Comprador preenche e finaliza compras. Vincule usuários às lojas pela tabela <code>user_stores</code> no Supabase.</p></article>{isAdmin&&<article className="panel wide"><h3>Histórico de alterações</h3>{auditLog.map(a=><div className="history-row" key={a.id}><span>{new Date(a.changed_at).toLocaleString("pt-BR")} · {a.table_name} · {a.action}</span><b>{a.record_id.slice(0,8)}</b></div>)}</article>}</div></>}
