import { CATEGORIES, money, num, totals, margin, profit } from "./constants";

export default function Dashboard({ stores, items, expenses, margins, selectedStoreId, range, showFinance }) {
  const storeIds = selectedStoreId === "all" ? stores.map(s=>s.id) : [selectedStoreId];
  const scopedItems = items.filter(i=>storeIds.includes(i.list?.store_id) && i.list?.purchase_date>=range.start && i.list?.purchase_date<=range.end && i.status==="comprado");
  const scopedExpenses = expenses.filter(e=>storeIds.includes(e.store_id) && e.expense_date>=range.start && e.expense_date<=range.end);
  const days=Math.max(1,Math.round((new Date(range.end)-new Date(range.start))/86400000)+1),prevEnd=new Date(range.start+"T12:00"),prevStart=new Date(range.start+"T12:00");prevEnd.setDate(prevEnd.getDate()-1);prevStart.setDate(prevStart.getDate()-days);
  const previousExpenses=expenses.filter(e=>storeIds.includes(e.store_id)&&e.expense_date>=prevStart.toISOString().slice(0,10)&&e.expense_date<=prevEnd.toISOString().slice(0,10));
  const previousItems=items.filter(i=>storeIds.includes(i.list?.store_id)&&i.list?.purchase_date>=prevStart.toISOString().slice(0,10)&&i.list?.purchase_date<=prevEnd.toISOString().slice(0,10)&&i.status==="comprado");
  const t=totals(scopedItems,margins), expenseTotal=scopedExpenses.reduce((a,e)=>a+Number(e.amount),0), net=t.sale-t.spent-expenseTotal, netMargin=t.sale?net/t.sale*100:0;
  const pt=totals(previousItems,margins),previousExpenseTotal=previousExpenses.reduce((a,e)=>a+Number(e.amount),0),previousNet=pt.sale-pt.spent-previousExpenseTotal,netChange=previousNet?(net-previousNet)/Math.abs(previousNet)*100:0;
  const storeData=stores.filter(s=>storeIds.includes(s.id)).map(s=>{const si=scopedItems.filter(i=>i.list?.store_id===s.id), se=scopedExpenses.filter(e=>e.store_id===s.id), st=totals(si,margins), ex=se.reduce((a,e)=>a+Number(e.amount),0);return{name:s.name,spent:st.spent,sale:st.sale,gross:st.gross,expenses:ex,net:st.sale-st.spent-ex,margin:st.sale?(st.sale-st.spent-ex)/st.sale*100:0}});
  const cats=Object.keys(CATEGORIES).map(c=>({name:CATEGORIES[c],total:scopedItems.filter(i=>i.product?.category===c).reduce((a,i)=>a+Number(i.paid_total),0)})).filter(x=>x.total).sort((a,b)=>b.total-a.total);
  const expenseCats=[...new Set(scopedExpenses.map(e=>e.category?.name))].map(name=>({name,total:scopedExpenses.filter(e=>e.category?.name===name).reduce((a,e)=>a+Number(e.amount),0)})).sort((a,b)=>b.total-a.total);
  const dates=[...new Set([...scopedItems.map(i=>i.list?.purchase_date),...scopedExpenses.map(e=>e.expense_date)])].filter(Boolean).sort();
  const evolution=dates.map(date=>({name:new Date(date+"T12:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"}),total:scopedItems.filter(i=>i.list?.purchase_date===date).reduce((a,i)=>a+Number(i.paid_total),0)+scopedExpenses.filter(e=>e.expense_date===date).reduce((a,e)=>a+Number(e.amount),0)}));
  const lowMargin=[...scopedItems].sort((a,b)=>profit(a,margins)-profit(b,margins)).slice(0,6);
  const promo=[...scopedItems].filter(i=>i.product?.type==="promocao"||profit(i,margins)>Number(i.paid_total)*(margin(i,margins)+15)/100).slice(0,6);
  return <><div className="page-head"><div><p className="eyebrow">{selectedStoreId==="all"?"Visão geral das lojas":"Painel individual da loja"}</p><h1>Dashboard</h1><p>Indicadores de {new Date(range.start+"T12:00").toLocaleDateString("pt-BR")} até {new Date(range.end+"T12:00").toLocaleDateString("pt-BR")}.</p></div></div>
    <div className="stats dashboard-stats"><Stat label="Venda estimada" value={money(t.sale)} note="faturamento previsto"/><Stat label="Gasto CEASA" value={money(t.spent)} note="compras finalizadas"/><Stat label="Despesas" value={showFinance?money(expenseTotal):"Restrito"} note="acesso gerencial"/><Stat label="Lucro bruto" value={money(t.gross)} note="venda - CEASA"/><Stat label="Lucro líquido" value={showFinance?money(net):"Restrito"} note={showFinance?`${netChange>=0?"+":""}${num(netChange)}% vs. período anterior`:"acesso gerencial"}/><Stat label="Margem líquida" value={showFinance?`${num(netMargin)}%`:"Restrito"} note="lucro / venda"/></div>
    <div className="dashboard-grid"><article className="panel wide"><h3>Comparativo entre lojas</h3><div className="store-comparison">{storeData.map(s=><div className="store-score" key={s.name}><h3>{s.name}</h3><div><span>CEASA</span><b>{money(s.spent)}</b></div><div><span>Despesas</span><b>{showFinance?money(s.expenses):"Restrito"}</b></div><div><span>Lucro líquido</span><b>{showFinance?money(s.net):"Restrito"}</b></div><div><span>Margem</span><b>{showFinance?`${num(s.margin)}%`:"Restrito"}</b></div></div>)}</div></article><article className="panel wide"><h3>Evolução por período: gastos CEASA + despesas</h3><Bars data={evolution}/></article><article className="panel"><h3>Categorias CEASA</h3><Bars data={cats}/></article>{showFinance&&<article className="panel"><h3>Categorias financeiras</h3><Bars data={expenseCats}/></article>}<article className="panel"><h3>Destaques</h3><div className="rank-row"><span>Loja que mais gastou</span><b>{[...storeData].sort((a,b)=>b.spent-a.spent)[0]?.name||"-"}</b></div>{showFinance&&<div className="rank-row"><span>Melhor margem</span><b>{[...storeData].sort((a,b)=>b.margin-a.margin)[0]?.name||"-"}</b></div>}<div className="rank-row"><span>Produtos comprados</span><b>{scopedItems.length}</b></div></article><article className="panel"><h3>Produtos mais comprados</h3>{[...scopedItems].sort((a,b)=>Number(b.purchased_quantity)-Number(a.purchased_quantity)).slice(0,6).map(i=><div className="rank-row" key={i.id}><span>{i.product?.name}</span><b>{num(i.purchased_quantity)}</b></div>)}</article><article className="panel"><h3>Produtos com menor lucro</h3>{lowMargin.map(i=><div className="rank-row" key={i.id}><span>{i.product?.name}</span><b>{money(profit(i,margins))}</b></div>)}</article><article className="panel"><h3>Podem entrar em promoção</h3>{promo.map(i=><div className="rank-row" key={i.id}><span>{i.product?.name}</span><b>{money(profit(i,margins))}</b></div>)}</article></div>
  </>;
}
function Stat({label,value,note}) { return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>; }
function Bars({data}) { const max=Math.max(...data.map(x=>x.total),1);return data.length?<div>{data.slice(0,8).map(x=><div className="bar-row" key={x.name}><b>{x.name}</b><div className="bar"><i style={{width:`${x.total/max*100}%`}}/></div><span>{money(x.total)}</span></div>)}</div>:<p className="muted">Sem dados no período.</p>; }
