import { useState } from "react";
import { supabase } from "./supabase";
import Finance from "./Finance";
import { money, productTotal } from "./constants";

const today=()=>new Date().toISOString().slice(0,10);
const sum=(rows,key="amount")=>rows.reduce((a,x)=>a+Number(x[key]||0),0);
const entryEmpty={entry_date:today(),store_id:"",category_id:"",description:"",amount:"",receipt_method:"PIX",observation:""};
const revenueEmpty={revenue_date:today(),store_id:"",cash_amount:"",pix_amount:"",debit_amount:"",credit_amount:"",other_amount:"",observation:""};
const openingEmpty={opening_date:today(),store_id:"",opening_amount:"",observation:""};
const closingEmpty={closing_date:today(),store_id:"",expected_total:"",counted_cash:"",pix_received:"",debit_received:"",credit_received:"",other_received:"",observation:""};

export default function FinanceCenter(p){
  const [tab,setTab]=useState("centro"),[query,setQuery]=useState(""),[entryCategory,setEntryCategory]=useState(""),[page,setPage]=useState(1);
  const visible=x=>(p.selectedStoreId==="all"||x.store_id===p.selectedStoreId);
  const inRange=(x,key)=>x[key]>=p.range.start&&x[key]<=p.range.end;
  const entries=p.entries.filter(x=>visible(x)&&inRange(x,"entry_date"));
  const expenses=p.expenses.filter(x=>visible(x)&&inRange(x,"expense_date"));
  const revenues=p.dailyRevenue.filter(x=>visible(x)&&inRange(x,"revenue_date"));
  const flow=p.cashFlow.filter(x=>visible(x)&&inRange(x,"movement_date"));
  const totalEntries=sum(entries),totalExpenses=sum(expenses),totalRevenue=sum(revenues,"total_amount");
  const ceasa=p.items.filter(i=>i.status!=="nao_comprar"&&visible({store_id:i.list?.store_id})&&i.list?.purchase_date>=p.range.start&&i.list?.purchase_date<=p.range.end).reduce((a,i)=>a+productTotal(i),0);
  const sales=totalRevenue||totalEntries, gross=sales-ceasa,net=gross-totalExpenses, balance=flow.reduce((a,x)=>a+(x.movement_type==="entrada"?Number(x.amount):-Number(x.amount)),0);
  const alerts=makeAlerts(expenses,revenues,balance,sales,net);
  const tabs=[["centro","Centro Financeiro"],["entradas","Entradas"],["despesas","Despesas"],["fluxo","Fluxo de Caixa"],["faturamento","Faturamento Diário"],["caixa","Caixa Diário"],["resultado","Resultado do Mês"]];
  const common={...p,entries,expenses,revenues,flow,totalEntries,totalExpenses,totalRevenue,ceasa,sales,gross,net,balance};
  return <div className="finance-center">
    <div className="page-head"><div><p className="eyebrow">Gestão integrada por loja</p><h1>Centro Financeiro</h1><p>Entradas, despesas, caixa, faturamento e resultado em um só lugar.</p></div><div className="head-actions"><button className="btn secondary" onClick={()=>exportCsv(flow,"fluxo-caixa")}>Exportar Excel</button><button className="btn ghost" onClick={()=>window.print()}>Imprimir / PDF</button></div></div>
    <div className="finance-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==="centro"&&<Center {...common} alerts={alerts}/>}
    {tab==="entradas"&&<Entries {...common} query={query} setQuery={setQuery} category={entryCategory} setCategory={setEntryCategory} page={page} setPage={setPage}/>}
    {tab==="despesas"&&<Finance {...p}/>}
    {tab==="fluxo"&&<CashFlow {...common}/>}
    {tab==="faturamento"&&<Revenue {...common}/>}
    {tab==="caixa"&&<DailyCash {...common}/>}
    {tab==="resultado"&&<Result {...common}/>}
  </div>
}

function Center(p){return <><Cards p={p}/><div className="finance-dashboard-grid"><article className="panel wide"><h3>Alertas automáticos</h3>{p.alerts.length?p.alerts.map((a,i)=><div className={`alert-row ${a.level}`} key={i}><b>{a.title}</b><span>{a.text}</span></div>):<p className="good-message">Nenhum alerta financeiro no período.</p>}</article><article className="panel"><h3>Entradas x Saídas</h3><Bars data={[{name:"Entradas",total:p.totalEntries},{name:"Saídas",total:p.totalExpenses}]}/></article><article className="panel"><h3>Comparativo entre lojas</h3><Bars data={p.stores.map(s=>({name:s.name,total:sum(p.revenues.filter(r=>r.store_id===s.id),"total_amount")||sum(p.entries.filter(e=>e.store_id===s.id))}))}/></article><article className="panel wide"><h3>Evolução financeira</h3><Timeline rows={p.flow}/></article></div></>}
function Cards({p}){return <div className="stats finance-stats"><Stat l="Faturamento" v={money(p.sales)}/><Stat l="Compras CEASA" v={money(p.ceasa)}/><Stat l="Despesas" v={money(p.totalExpenses)}/><Stat l="Lucro bruto" v={money(p.gross)}/><Stat l="Lucro líquido" v={money(p.net)}/><Stat l="Margem líquida" v={`${p.sales?(p.net/p.sales*100).toFixed(1):0}%`}/><Stat l="Saldo de caixa" v={money(p.balance)}/></div>}

function Entries(p){
  const [form,setForm]=useState(entryEmpty),[editing,setEditing]=useState(null),[file,setFile]=useState(null);
  const rows=p.entries.filter(e=>(!p.query||`${e.description} ${e.observation}`.toLowerCase().includes(p.query.toLowerCase()))&&(!p.category||e.category_id===p.category));
  const pages=Math.max(1,Math.ceil(rows.length/10)),shown=rows.slice((p.page-1)*10,p.page*10);
  const save=async e=>{e.preventDefault();const storeId=p.selectedStoreId==="all"?form.store_id:p.selectedStoreId;if(!storeId)return p.flash("Selecione uma loja.");let receipt_path=editing?.receipt_path||null;if(file){const path=`${storeId}/${Date.now()}-${file.name.replace(/[^\w.-]/g,"_")}`;const up=await supabase.storage.from("financial-receipts").upload(path,file);if(up.error)return p.flash(up.error.message);receipt_path=path}const payload={...form,store_id:storeId,amount:Number(form.amount),created_by:editing?.created_by||p.profile.id,receipt_path};const r=editing?await supabase.from("financial_entries").update(payload).eq("id",editing.id):await supabase.from("financial_entries").insert(payload);if(r.error)p.flash(r.error.message);else{p.flash(editing?"Entrada atualizada.":"Entrada cadastrada.");setForm(entryEmpty);setEditing(null);setFile(null);p.reload()}};
  const edit=x=>{setEditing(x);setForm({entry_date:x.entry_date,store_id:x.store_id,category_id:x.category_id,description:x.description,amount:x.amount,receipt_method:x.receipt_method,observation:x.observation||""})};
  const remove=async x=>{if(!confirm(`Excluir a entrada "${x.description}"?`))return;const r=await supabase.from("financial_entries").delete().eq("id",x.id);r.error?p.flash(r.error.message):(p.flash("Entrada excluída."),p.reload())};
  return <><div className="stats"><Stat l="Total de entradas" v={money(sum(rows))} n={`${rows.length} lançamentos`}/><Stat l="PIX" v={money(sum(rows.filter(x=>x.receipt_method==="PIX")))}/><Stat l="Dinheiro" v={money(sum(rows.filter(x=>x.receipt_method==="Dinheiro")))}/></div><form className="panel financial-form" onSubmit={save}><div className="panel-head"><h3>{editing?"Editar entrada":"Nova entrada"}</h3>{editing&&<button type="button" className="btn ghost" onClick={()=>{setEditing(null);setForm(entryEmpty)}}>Cancelar</button>}</div><div className="form-grid"><label>Data<input required type="date" value={form.entry_date} onChange={e=>setForm({...form,entry_date:e.target.value})}/></label>{p.selectedStoreId==="all"&&<StoreField stores={p.stores} value={form.store_id} set={v=>setForm({...form,store_id:v})}/>}<label>Categoria<select required value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Selecione</option>{p.entryCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="span2">Descrição<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Valor<input required min="0" step=".01" type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Forma de recebimento<select value={form.receipt_method} onChange={e=>setForm({...form,receipt_method:e.target.value})}>{["Dinheiro","PIX","Cartão débito","Cartão crédito","Transferência","Outros"].map(x=><option key={x}>{x}</option>)}</select></label><label>Comprovante<input type="file" accept="image/*,.pdf" onChange={e=>setFile(e.target.files[0])}/></label><label className="span2">Observação<textarea value={form.observation} onChange={e=>setForm({...form,observation:e.target.value})}/></label></div><button className="btn primary full">Salvar entrada</button></form><div className="toolbar"><label className="search"><input placeholder="Buscar entrada..." value={p.query} onChange={e=>{p.setQuery(e.target.value);p.setPage(1)}}/></label><select value={p.category} onChange={e=>p.setCategory(e.target.value)}><option value="">Todas as categorias</option>{p.entryCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="btn secondary" onClick={()=>exportCsv(rows,"entradas")}>Exportar Excel</button></div><div className="expense-list">{shown.map(x=><Row key={x.id} title={x.description} text={`${date(x.entry_date)} · ${x.store?.name||""} · ${x.category?.name||x.receipt_method}`} value={x.amount} edit={()=>edit(x)} remove={()=>remove(x)}/>)}</div><Pagination page={p.page} pages={pages} set={p.setPage}/></>
}

function CashFlow(p){const cumulative=p.flow.reduce((a,x)=>a+(x.movement_type==="entrada"?Number(x.amount):-Number(x.amount)),0);return <><Cards p={p}/><div className="finance-dashboard-grid"><article className="panel wide"><h3>Evolução diária</h3><Timeline rows={p.flow}/></article><article className="panel"><h3>Saldo acumulado</h3><strong className={`giant-value ${cumulative<0?"negative":""}`}>{money(cumulative)}</strong><Bars data={[{name:"Entradas",total:sum(p.flow.filter(x=>x.movement_type==="entrada"))},{name:"Saídas",total:sum(p.flow.filter(x=>x.movement_type==="saida"))}]}/></article></div><div className="expense-list">{p.flow.map(x=><Row key={x.id} title={x.description} text={`${date(x.movement_date)} · ${x.category}`} value={(x.movement_type==="saida"?-1:1)*x.amount}/>)}</div></>}

function Revenue(p){const [form,setForm]=useState(revenueEmpty);const total=["cash_amount","pix_amount","debit_amount","credit_amount","other_amount"].reduce((a,k)=>a+Number(form[k]||0),0);const save=async e=>{e.preventDefault();const store_id=p.selectedStoreId==="all"?form.store_id:p.selectedStoreId;if(!store_id)return p.flash("Selecione uma loja.");const payload={...form,store_id,created_by:p.profile.id};const r=await supabase.from("daily_revenue").upsert(payload,{onConflict:"store_id,revenue_date"});r.error?p.flash(r.error.message):(p.flash("Faturamento diário salvo."),setForm(revenueEmpty),p.reload())};return <><div className="stats"><Stat l="Faturamento no período" v={money(p.totalRevenue)}/><Stat l="Média diária" v={money(p.revenues.length?p.totalRevenue/p.revenues.length:0)}/><Stat l="Fechamentos" v={p.revenues.length}/></div><form className="panel financial-form" onSubmit={save}><h3>Fechamento rápido do dia</h3><div className="form-grid"><label>Data<input type="date" value={form.revenue_date} onChange={e=>setForm({...form,revenue_date:e.target.value})}/></label>{p.selectedStoreId==="all"&&<StoreField stores={p.stores} value={form.store_id} set={v=>setForm({...form,store_id:v})}/>} {["cash_amount","pix_amount","debit_amount","credit_amount","other_amount"].map((k,i)=><label key={k}>{["Dinheiro","PIX","Cartão débito","Cartão crédito","Outros"][i]}<input type="number" min="0" step=".01" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><div className="form-total">Faturamento total: <strong>{money(total)}</strong></div><button className="btn primary full">Salvar faturamento</button></form><article className="panel"><h3>Evolução do faturamento</h3><Timeline rows={p.revenues.map(x=>({movement_date:x.revenue_date,movement_type:"entrada",amount:x.total_amount}))}/></article></>}

function DailyCash(p){const [open,setOpen]=useState(openingEmpty),[close,setClose]=useState(closingEmpty);const closeStore=p.selectedStoreId==="all"?close.store_id:p.selectedStoreId,opening=sum(p.cashOpenings.filter(x=>x.store_id===closeStore&&x.opening_date===close.closing_date),"opening_amount"),dayEntries=sum(p.entries.filter(x=>x.store_id===closeStore&&x.entry_date===close.closing_date)),dayExpenses=sum(p.expenses.filter(x=>x.store_id===closeStore&&x.expense_date===close.closing_date)),expected=opening+dayEntries-dayExpenses;const save=async(type)=>{const form=type==="open"?open:{...close,expected_total:expected},store_id=p.selectedStoreId==="all"?form.store_id:p.selectedStoreId;if(!store_id)return p.flash("Selecione uma loja.");const table=type==="open"?"cash_openings":"cash_closings",conflict=type==="open"?"store_id,opening_date":"store_id,closing_date";const r=await supabase.from(table).upsert({...form,store_id,created_by:p.profile.id},{onConflict:conflict});r.error?p.flash(r.error.message):(p.flash(type==="open"?"Abertura salva.":"Fechamento salvo."),p.reload())};const informed=["counted_cash","pix_received","debit_received","credit_received","other_received"].reduce((a,k)=>a+Number(close[k]||0),0),diff=informed-expected;return <div className="finance-layout"><form className="panel financial-form" onSubmit={e=>{e.preventDefault();save("open")}}><h3>Abertura de caixa</h3><label>Data<input type="date" value={open.opening_date} onChange={e=>setOpen({...open,opening_date:e.target.value})}/></label>{p.selectedStoreId==="all"&&<StoreField stores={p.stores} value={open.store_id} set={v=>setOpen({...open,store_id:v})}/>}<label>Valor inicial<input type="number" step=".01" value={open.opening_amount} onChange={e=>setOpen({...open,opening_amount:e.target.value})}/></label><button className="btn primary full">Salvar abertura</button></form><form className="panel financial-form" onSubmit={e=>{e.preventDefault();save("close")}}><h3>Fechamento de caixa</h3><div className="form-grid"><label>Data<input type="date" value={close.closing_date} onChange={e=>setClose({...close,closing_date:e.target.value})}/></label>{p.selectedStoreId==="all"&&<StoreField stores={p.stores} value={close.store_id} set={v=>setClose({...close,store_id:v})}/>}<label>Total esperado<input readOnly value={expected.toFixed(2)}/></label>{["counted_cash","pix_received","debit_received","credit_received","other_received"].map((k,i)=><label key={k}>{["Dinheiro contado","PIX recebido","Débito","Crédito","Outras entradas"][i]}<input type="number" step=".01" value={close[k]} onChange={e=>setClose({...close,[k]:e.target.value})}/></label>)}</div><div className={`cash-difference ${Math.abs(diff)>.01?"danger":"ok"}`}><span>Total informado: {money(informed)}</span><strong>Diferença: {money(diff)}</strong></div><button className="btn primary full">Salvar fechamento</button></form></div>}

function Result(p){const taxes=sum(p.expenses.filter(x=>x.category?.name==="Impostos")),operating=p.totalExpenses-taxes,operatingProfit=p.sales-p.ceasa-operating,net=operatingProfit-taxes;const rows=[["Faturamento",p.sales],["Compras CEASA",-p.ceasa],["Despesas operacionais",-operating],["Lucro operacional",operatingProfit],["Impostos",-taxes],["Lucro líquido",net]];return <><div className="stats"><Stat l="Lucro operacional" v={money(operatingProfit)}/><Stat l="Lucro líquido" v={money(net)}/><Stat l="Margem líquida" v={`${p.sales?(net/p.sales*100).toFixed(1):0}%`}/></div><article className="panel result-statement"><h3>Resultado do período</h3>{rows.map(([name,value])=><div key={name} className={name.includes("Lucro")?"result-total":""}><span>{name}</span><b className={value<0?"negative":""}>{money(value)}</b><small>{p.sales?`${(value/p.sales*100).toFixed(1)}%`:"0%"}</small></div>)}</article></>}

function makeAlerts(expenses,revenues,balance,sales,net){const out=[],now=today(),week=new Date();week.setDate(week.getDate()+7);const soon=week.toISOString().slice(0,10);const overdue=expenses.filter(x=>x.status==="vencido"),upcoming=expenses.filter(x=>x.status==="pendente"&&x.expense_date>=now&&x.expense_date<=soon);if(overdue.length)out.push({level:"danger",title:"Contas vencidas",text:`${overdue.length} conta(s), total ${money(sum(overdue))}.`});if(upcoming.length)out.push({level:"warning",title:"Contas a vencer",text:`${upcoming.length} conta(s) nos próximos 7 dias.`});if(balance<0)out.push({level:"danger",title:"Caixa negativo",text:`Saldo atual de ${money(balance)}.`});if(sales&&net/sales<.1)out.push({level:"warning",title:"Margem abaixo do esperado",text:`Margem líquida atual de ${(net/sales*100).toFixed(1)}%.`});if(!revenues.length)out.push({level:"warning",title:"Faturamento não lançado",text:"Cadastre o fechamento diário para acompanhar resultados reais."});return out}
function Timeline({rows}){const grouped=Object.values(rows.reduce((a,x)=>{const d=x.movement_date;a[d]??={date:d,entrada:0,saida:0};a[d][x.movement_type]+=Number(x.amount||0);return a},{})).sort((a,b)=>a.date.localeCompare(b.date)).slice(-14),max=Math.max(...grouped.flatMap(x=>[x.entrada,x.saida]),1);return grouped.length?<div className="timeline-chart">{grouped.map(x=><div className="timeline-day" key={x.date}><div className="timeline-bars"><i className="income" style={{height:`${x.entrada/max*100}%`}}/><i className="outcome" style={{height:`${x.saida/max*100}%`}}/></div><small>{x.date.slice(5).replace("-","/")}</small></div>)}</div>:<p className="muted">Sem movimentações no período.</p>}
function Bars({data}){const max=Math.max(...data.map(x=>x.total),1);return <div>{data.filter(x=>x.total).map(x=><div className="bar-row" key={x.name}><b>{x.name}</b><div className="bar"><i style={{width:`${x.total/max*100}%`}}/></div><span>{money(x.total)}</span></div>)}</div>}
function Row({title,text,value,edit,remove}){return <article className="expense-row"><div><h3>{title}</h3><p>{text}</p></div><strong className={value<0?"negative":""}>{money(value)}</strong>{(edit||remove)&&<div className="row-actions">{edit&&<button className="btn secondary" onClick={edit}>Editar</button>}{remove&&<button className="btn danger" onClick={remove}>Excluir</button>}</div>}</article>}
function StoreField({stores,value,set}){return <label>Loja<select required value={value} onChange={e=>set(e.target.value)}><option value="">Selecione</option>{stores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>}
function Pagination({page,pages,set}){return pages>1&&<div className="pagination"><button disabled={page===1} onClick={()=>set(page-1)}>Anterior</button><span>{page} de {pages}</span><button disabled={page===pages} onClick={()=>set(page+1)}>Próxima</button></div>}
function Stat({l,v,n=""}){return <div className="stat"><span>{l}</span><strong>{v}</strong><small>{n}</small></div>}
function date(x){return new Date(x+"T12:00").toLocaleDateString("pt-BR")}
function exportCsv(rows,name){const keys=Object.keys(rows[0]||{}).filter(k=>!["store","category"].includes(k));const csv=[keys,...rows.map(x=>keys.map(k=>x[k]))].map(r=>r.map(x=>`"${String(x??"").replaceAll('"','""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=`${name}.csv`;a.click()}
